config/routes.rb
AcceptsNestedAttributesFor::Application.routes.draw do
  resources :trees

  resources :forests

end

app/models/forest.rb
class Forest < ActiveRecord::Base
  has_many :trees
  
  accepts_nested_attributes_for :trees, allow_destroy: true

  validates_presence_of :name, :size, :climate, :latitude, :longitude
end

app/models/tree.rb
class Tree < ActiveRecord::Base
  belongs_to :forest

  validates_presence_of :common_name, :scientific_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forests_controller.rb
class ForestsController < ApplicationController
  before_action :set_forest, only: [:show, :edit, :update, :destroy]

  # GET /forests
  # GET /forests.json
  def index
    @forests = Forest.all
  end

  # GET /forests/1
  # GET /forests/1.json
  def show
  end

  # GET /forests/new
  def new
    @forest = Forest.new
    # 3.times { @forest.trees.build }
  end

  # GET /forests/1/edit
  def edit
  end

  # POST /forests
  # POST /forests.json
  def create
    @forest = Forest.new(forest_params)

    respond_to do |format|
      if @forest.save
        format.html { redirect_to @forest, notice: 'Forest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @forest }
      else
        format.html { render action: 'new' }
        format.json { render json: @forest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forests/1
  # PATCH/PUT /forests/1.json
  def update
    respond_to do |format|
      if @forest.update(forest_params)
        format.html { redirect_to @forest, notice: 'Forest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @forest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forests/1
  # DELETE /forests/1.json
  def destroy
    @forest.destroy
    respond_to do |format|
      format.html { redirect_to forests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forest
      @forest = Forest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forest_params
      params.require(:forest).permit(:name, :size, :latitude, :longitude, :climate,
                                     trees_attributes: [:forest_id, :common_name, :scientific_name])
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]

  # GET /trees
  # GET /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tree }
      else
        format.html { render action: 'new' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.require(:tree).permit(:common_name, :scientific_name, :forest_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forests_helper.rb
module ForestsHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/forests/_form.html.erb
<%= simple_nested_form_for(@forest, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @forest.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@forest.errors.count, "error") %> prohibited this forest from being saved:</h4>

      <ul>
      <% @forest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :size, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :size, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :latitude, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :latitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :longitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :climate, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :climate, :class => "form-control" %>
    </div>
  </div>

  <%= f.fields_for :trees do |t| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        Tree
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= t.label :common_name, :class => "col-lg-2 control-label" %>
          <div class="col-lg-10">
            <%= t.text_field :common_name, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= t.label :scientific_name, :class => "col-lg-2 control-label" %>
          <div class="col-lg-10">
            <%= t.text_field :scientific_name, :class => "form-control" %>
          </div>
        </div>
      </div>
    </div>

  <% end %>
<td><%= f.link_to_add 'Add', :trees %></td>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/forests/edit.html.erb
<div class="page-header">
  <%= link_to forests_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @forest, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing forest</h1>
</div>

<%= render 'form' %>

app/views/forests/index.html.erb
<div class="page-header">
  <%= link_to new_forest_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Forest
  <% end %>
  <h1>Listing forests</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Size</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Climate</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @forests) do |forest| %>
            <td><%= forest.name %></td>
            <td><%= forest.size %></td>
            <td><%= forest.latitude %></td>
            <td><%= forest.longitude %></td>
            <td><%= forest.climate %></td>
            <td><%= link_to 'Show', forest %></td>
        <td><%= link_to 'Edit', edit_forest_path(forest) %></td>
        <td><%= link_to 'Destroy', forest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/forests/new.html.erb
<div class="page-header">
  <%= link_to forests_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New forest</h1>
</div>

<%= render 'form' %>

app/views/forests/show.html.erb
<div class="page-header">
  <%= link_to forests_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_forest_path(@forest), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show forest</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @forest.name %></dd>

  <dt>Size:</dt>
  <dd><%= @forest.size %></dd>

  <dt>Latitude:</dt>
  <dd><%= @forest.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @forest.longitude %></dd>

  <dt>Climate:</dt>
  <dd><%= @forest.climate %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/trees/_form.html.erb
<%= form_for(@tree, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @tree.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@tree.errors.count, "error") %> prohibited this tree from being saved:</h4>

      <ul>
      <% @tree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :common_name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :common_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :scientific_name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :scientific_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :forest_id, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :forest_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/trees/edit.html.erb
<div class="page-header">
  <%= link_to trees_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @tree, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing tree</h1>
</div>

<%= render 'form' %>

app/views/trees/index.html.erb
<div class="page-header">
  <%= link_to new_tree_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Tree
  <% end %>
  <h1>Listing trees</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Common name</th>
            <th>Scientific name</th>
            <th>Forest</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @trees) do |tree| %>
            <td><%= tree.common_name %></td>
            <td><%= tree.scientific_name %></td>
            <td><%= tree.forest_id %></td>
            <td><%= link_to 'Show', tree %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
        <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trees/new.html.erb
<div class="page-header">
  <%= link_to trees_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New tree</h1>
</div>

<%= render 'form' %>

app/views/trees/show.html.erb
<div class="page-header">
  <%= link_to trees_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_tree_path(@tree), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show tree</h1>
</div>

<dl class="dl-horizontal">
  <dt>Common name:</dt>
  <dd><%= @tree.common_name %></dd>

  <dt>Scientific name:</dt>
  <dd><%= @tree.scientific_name %></dd>

  <dt>Forest:</dt>
  <dd><%= @tree.forest_id %></dd>

</dl>